---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eebrfuekkk/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R .env $DEPLOYPATH 2>/dev/null || true